UPDATE [dbo].[cust_equivalent_response_codes] SET [commision_value] = CAST(0 AS Numeric(18, 0)) WHERE id = 9
UPDATE [dbo].[cust_equivalent_response_codes] SET [commision_value] = CAST(0 AS Numeric(18, 0)) WHERE id = 14
UPDATE [dbo].[cust_equivalent_response_codes] SET [commision_value] = CAST(0 AS Numeric(18, 0)) WHERE id = 15
UPDATE [dbo].[cust_equivalent_response_codes] SET [commision_value] = CAST(0 AS Numeric(18, 0)) WHERE id = 16
UPDATE [dbo].[cust_equivalent_response_codes] SET [commision_value] = CAST(0 AS Numeric(18, 0)) WHERE id = 20
UPDATE [dbo].[cust_equivalent_response_codes] SET [commision_value] = CAST(0 AS Numeric(18, 0)) WHERE id = 36
UPDATE [dbo].[cust_equivalent_response_codes] SET [commision_value] = CAST(0 AS Numeric(18, 0)) WHERE id = 39
UPDATE [dbo].[cust_equivalent_response_codes] SET [commision_value] = CAST(0 AS Numeric(18, 0)) WHERE id = 40
UPDATE [dbo].[cust_equivalent_response_codes] SET [commision_value] = CAST(0 AS Numeric(18, 0)) WHERE id = 41
UPDATE [dbo].[cust_equivalent_response_codes] SET [commision_value] = CAST(0 AS Numeric(18, 0)) WHERE id = 42
UPDATE [dbo].[cust_equivalent_response_codes] SET [commision_value] = CAST(0 AS Numeric(18, 0)) WHERE id = 49
UPDATE [dbo].[cust_equivalent_response_codes] SET [commision_value] = CAST(0 AS Numeric(18, 0)) WHERE id = 53
UPDATE [dbo].[cust_equivalent_response_codes] SET [commision_value] = CAST(0 AS Numeric(18, 0)) WHERE id = 80
UPDATE [dbo].[cust_equivalent_response_codes] SET [commision_value] = CAST(0 AS Numeric(18, 0)) WHERE id = 81
UPDATE [dbo].[cust_equivalent_response_codes] SET [commision_value] = CAST(0 AS Numeric(18, 0)) WHERE id = 82
UPDATE [dbo].[cust_equivalent_response_codes] SET [commision_value] = CAST(0 AS Numeric(18, 0)) WHERE id = 84
UPDATE [dbo].[cust_equivalent_response_codes] SET [commision_value] = CAST(0 AS Numeric(18, 0)) WHERE id = 88
UPDATE [dbo].[cust_equivalent_response_codes] SET [commision_value] = CAST(0 AS Numeric(18, 0)) WHERE id = 106
UPDATE [dbo].[cust_equivalent_response_codes] SET [commision_value] = CAST(0 AS Numeric(18, 0)) WHERE id = 110
UPDATE [dbo].[cust_equivalent_response_codes] SET [code_isc]= N'8102' WHERE id = 115
UPDATE [dbo].[cust_equivalent_response_codes] SET [commision_value] = CAST(0 AS Numeric(18, 0)) WHERE id = 129
UPDATE [dbo].[cust_equivalent_response_codes] SET [commision_value] = CAST(0 AS Numeric(18, 0)) WHERE id = 130
UPDATE [dbo].[cust_equivalent_response_codes] SET [commision_value] = CAST(0 AS Numeric(18, 0)) WHERE id = 132
UPDATE [dbo].[cust_equivalent_response_codes] SET [commision_value] = CAST(0 AS Numeric(18, 0)) WHERE id = 133
UPDATE [dbo].[cust_equivalent_response_codes] SET [commision_value] = CAST(0 AS Numeric(18, 0)) WHERE id = 136
UPDATE [dbo].[cust_equivalent_response_codes] SET [commision_value] = CAST(0 AS Numeric(18, 0)) WHERE id = 137
UPDATE [dbo].[cust_equivalent_response_codes] SET [code_iso] = N'14', [code_b24] = N'2013' WHERE id = 147
UPDATE [dbo].[cust_equivalent_response_codes] SET [commision_value] = CAST(0 AS Numeric(18, 0)) WHERE id = 161
UPDATE [dbo].[cust_equivalent_response_codes] SET [commision_value] = CAST(0 AS Numeric(18, 0)) WHERE id = 166
UPDATE [dbo].[cust_equivalent_response_codes] SET [commision_value] = CAST(0 AS Numeric(18, 0)) WHERE id = 168
UPDATE [dbo].[cust_equivalent_response_codes] SET [commision_value] = CAST(0 AS Numeric(18, 0)) WHERE id = 169
UPDATE [dbo].[cust_equivalent_response_codes] SET [commision_value] = CAST(0 AS Numeric(18, 0)) WHERE id = 170
UPDATE [dbo].[cust_equivalent_response_codes] SET [commision_value] = CAST(0 AS Numeric(18, 0)) WHERE id = 174
UPDATE [dbo].[cust_equivalent_response_codes] SET [commision_value] = CAST(0 AS Numeric(18, 0)) WHERE id = 176